project:
  type: website
  output-dir: docs

website:
  title: "Shane W. Devlin, Postdoc at LBNL "
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: resume/website_CV.pdf
        text: Cirriculum Vitae
      - publications.qmd
      - href: fun_blog.qmd
        text: Fun Blog
  sidebar: false
format:
  html:
    theme: journal
    css: styles.css
    fontsize: 16px
    toc: true

editor: visual

