project:
  type: website
  output-dir: docs

website:
  title: "Shane Devlin, UC Berkeley Chemistry "
  about:
  
  favicon: twitter.png
  twitter-card: true
  site-url: https://twitter.com/shanedevlin33 
  
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - href: fun_blog.qmd
        text: Personal Blog

format:
  html:
    theme: journal
    css: styles.css
    fontsize: 16px
    toc: true

editor: visual

