project:
  type: website
  output-dir: docs

website:
  title: "shaned16.github.io "
  about:
    
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - fun.qmd
      - href: fun_blog.qmd
        text: Personal Blog v2

format:
  html:
    theme: journal
    css: styles.css
    fontsize: 16px
    toc: true

editor: visual

