project:
  type: website
  output-dir: docs

website:
  title: "Shane Devlin, UC Berkeley Chemistry "
  about:
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - href: fun_blog.qmd
        text: Fun Blog

format:
  html:
    theme: journal
    css: styles.css
    fontsize: 16px
    toc: true

editor: visual

